---
title: Katie Angermeier Haab
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
bio: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
  incididunt ut labore et dolore magna aliqua. Fames ac turpis egestas sed. Pretium
  quam vulputate dignissim suspendisse. Rhoncus aenean vel elit scelerisque mauris
  pellentesque pulvinar pellentesque. Vitae nunc sed velit dignissim sodales. Porttitor
  massa id neque aliquam vestibulum morbi blandit. Mi ipsum faucibus vitae aliquet
  nec ullamcorper sit. Urna nunc id cursus metus aliquam eleifend. Quis lectus nulla
  at volutpat diam. Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet.
  Posuere ac ut consequat semper. Ac ut consequat semper viverra nam.
description: Katie is the best!
reading_time: false
words_per_minute: 200
logo: assets/img/logo.jpg
background: assets/img/background.jpg
tiled_bg: false
locale: en_UK
#url: https://katieangermeierhaab.com
url: http://127.0.0.1:4000/
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed
email: katie.angermeier@gmail.com
facebook: katie.angermeier
linkedin: katie-haab-97307a79
instagram: complikatie
gems:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
github:
- metadata
