---
title: Katie Angermeier Haab
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
bio: Accomplished director and writer with over 15 years of managing experience in
  coordinating small- and large-scale projects, workshops, events, and businesses. I'm
  a self-starter and team motivator with excellent communication skills--written and
  speaking--with people of varying backgrounds, ages, and demographics. I'm flexible,
  able to pivot whenever necessary, and I thrive in a lively, creative atmosphere.
description: Katie is the best!
reading_time: false
words_per_minute: 200
logo: assets/img/logo.jpg
background: assets/img/background.jpg
tiled_bg: false
locale: en_UK
url: http://katieangermeierhaab.com/
#url: http://127.0.0.1:4000
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed
email: katie.angermeier@gmail.com
facebook: katie.angermeier
linkedin: katie-haab-97307a79
instagram: complikatie
gems:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
github:
- metadata
